//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@interface CefHostView : NSView
{
    BOOL _fillWindow;
}

- (void)setFrame:(struct CGRect)arg1;
- (void)setFrameSize:(struct CGSize)arg1;
- (BOOL)acceptsFirstResponder;
- (void)swipeWithEvent:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 fillWindow:(BOOL)arg2;

@end

