//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSMenuDelegate.h"

@class NSMenuItem, NSWindow;

@interface ClientMenuHandler : NSObject <NSMenuDelegate>
{
    BOOL isLoggedIn_;
    NSMenuItem *devMenuItem_;
    NSWindow *applicationMainWindow_;
}

- (void)importPlaylists:(id)arg1;
- (void)handleDevCommand:(int)arg1;
- (void)toggleGrid:(id)arg1;
- (void)showApplications:(id)arg1;
- (void)showUtils:(id)arg1;
- (void)showDevTools:(id)arg1;
- (void)reload:(id)arg1;
- (void)redo:(id)arg1;
- (void)undo:(id)arg1;
- (void)terminate:(id)arg1;
- (void)unhideAllApplications:(id)arg1;
- (void)hideOtherApplications:(id)arg1;
- (void)reopen:(id)arg1;
- (void)hide:(id)arg1;
- (void)showFriendFeed:(id)arg1;
- (void)toggleFullScreen:(id)arg1;
- (void)performZoom:(id)arg1;
- (void)performMiniaturize:(id)arg1;
- (void)performClose:(id)arg1;
- (void)arrangeInFront:(id)arg1;
- (void)volumeDown:(id)arg1;
- (void)volumeUp:(id)arg1;
- (void)seekBackward:(id)arg1;
- (void)seekForward:(id)arg1;
- (void)skipPrevious:(id)arg1;
- (void)skipNext:(id)arg1;
- (void)toggleRepeat:(id)arg1;
- (void)toggleShuffle:(id)arg1;
- (void)togglePlayPause:(id)arg1;
- (void)toggleOfflineMode:(id)arg1;
- (void)togglePrivateSession:(id)arg1;
- (void)resetZoom:(id)arg1;
- (void)zoomOut:(id)arg1;
- (void)zoomIn:(id)arg1;
- (void)filter:(id)arg1;
- (void)search:(id)arg1;
- (void)selectAll:(id)arg1;
- (void)delete:(id)arg1;
- (void)paste:(id)arg1;
- (void)copy:(id)arg1;
- (void)cut:(id)arg1;
- (void)createFolder:(id)arg1;
- (void)createPlaylist:(id)arg1;
- (void)logOut:(id)arg1;
- (void)showHelp:(id)arg1;
- (void)showYourAccount:(id)arg1;
- (void)showLicenses:(id)arg1;
- (void)showCommunityPage:(id)arg1;
- (void)showAboutBox:(id)arg1;
- (void)showSettingsPage:(id)arg1;
- (void)goBack:(id)arg1;
- (void)goForward:(id)arg1;
- (BOOL)menu:(id)arg1 updateItem:(id)arg2 atIndex:(long long)arg3 shouldCancel:(BOOL)arg4;
- (long long)numberOfItemsInMenu:(id)arg1;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (void)logMenuInteraction:(struct InteractionType)arg1 withIntent:(struct UserIntent)arg2;
- (BOOL)popupWindowHasKeyFocus;
- (BOOL)isFocusOnEditableField;
- (void)performMenuAction:(SEL)arg1 withSender:(id)arg2 orControlMessage:(id)arg3;
- (void)performOnFirstResponder:(SEL)arg1 withSender:(id)arg2;
- (void)addSeparator:(id)arg1;
- (id)addItem:(int)arg1 action:(SEL)arg2 toMenu:(id)arg3;
- (id)addItem:(int)arg1 action:(SEL)arg2 keyEquivalentChar:(unsigned short)arg3 toMenu:(id)arg4;
- (id)addItem:(int)arg1 action:(SEL)arg2 keyEquivalent:(id)arg3 toMenu:(id)arg4;
- (void)setupImportPlaylistsMenu:(id)arg1;
- (void)setupDevelopMenu:(id)arg1;
- (void)setupHelpMenu:(id)arg1;
- (void)setupWindowMenu:(id)arg1;
- (void)setupPlaybackMenu:(id)arg1;
- (void)setupViewMenu:(id)arg1;
- (void)setupEditMenu:(id)arg1;
- (void)setupFileMenu:(id)arg1;
- (void)setupSpotifyMenu:(id)arg1;
- (id)applicationDockMenu:(id)arg1;
- (void)setupMenu;
- (void)setApplicationMainWindow:(id)arg1;
- (void)updateMenu;
- (void)setLoggedIn:(BOOL)arg1;
- (void)dealloc;

@end

