//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSWindowDelegate.h"

@class NSArray, NSWindow;

@interface ClientWindowDelegate : NSObject <NSWindowDelegate>
{
    NSWindow *window_;
    BOOL _shouldHideAfterExitingFullscreen;
    NSArray *_dummyArrayForWindowAnimation;
    BOOL _moving_window_buttons;
}

- (void)cleanup:(id)arg1;
- (void)window:(id)arg1 startCustomAnimationToExitFullScreenWithDuration:(double)arg2;
- (id)customWindowsToExitFullScreenForWindow:(id)arg1;
- (BOOL)windowShouldClose:(id)arg1;
- (void)fixTrackingAreaInWindow:(id)arg1;
- (void)positionButton:(id)arg1 inWindow:(id)arg2 offset:(double)arg3;
- (void)positionButtonsInWindow:(id)arg1;
- (void)positionButtonsNotification:(id)arg1;
- (void)alwaysPositionButton:(id)arg1;
- (void)alwaysPositionButtonsInWindow:(id)arg1;
- (void)windowDidExitFullScreen:(id)arg1;
- (void)windowDidEnterFullScreen:(id)arg1;
- (void)applicationDidUnhide:(id)arg1;
- (void)applicationDidHide:(id)arg1;
- (void)windowDidDeminiaturize:(id)arg1;
- (void)windowDidMiniaturize:(id)arg1;
- (void)windowDidResignKey:(id)arg1;
- (void)windowDidBecomeKey:(id)arg1;
- (void)windowDidResize:(id)arg1;
- (void)updateMenu;
- (void)notifyConsoleMessage:(id)arg1;
- (void)alert:(id)arg1 withMessage:(id)arg2;
- (void)dealloc;
- (id)initWithWindow:(id)arg1;

@end

