//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSApplication.h"

#import "CefAppProtocol.h"

@interface ClientApplication : NSApplication <CefAppProtocol>
{
    BOOL handlingSendEvent_;
}

+ (void)mediaKeyTap:(id)arg1 receivedMediaKeyEvent:(id)arg2;
+ (void)sendVisibilityControlMessage:(BOOL)arg1;
+ (void)initialize;
- (void)setShuffle:(BOOL)arg1;
- (BOOL)shuffle;
- (BOOL)shuffleEnabled;
- (void)setRepeat:(BOOL)arg1;
- (BOOL)repeat;
- (BOOL)repeatEnabled;
- (void)setPlaybackPosition:(id)arg1;
- (id)playbackPosition;
- (id)playerState;
- (void)setSoundVolume:(id)arg1;
- (id)soundVolume;
- (id)currentTrack;
- (void)setLoggedIn:(id)arg1;
- (void)terminate:(id)arg1;
- (void)sendEvent:(id)arg1;
- (void)setHandlingSendEvent:(BOOL)arg1;
- (BOOL)isHandlingSendEvent;
- (void)mediaKeyTap:(id)arg1 receivedMediaKeyEvent:(id)arg2;
- (void)_removeFromMediaTapsListeners;
- (void)_listenToMediaTaps;
- (void)_listenToActivationEvents;
- (void)_computerIsDeactivating:(id)arg1;
- (void)_computerIsActivating:(id)arg1;
- (id)init;

@end

