//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindow.h"

@interface NSWindow (DisableUserInteraction)
+ (void)load;
@property BOOL isUserInteractionEnabled;
- (void)sendEvent_swizzle:(id)arg1;
- (void)updateMenu:(id)arg1 setEnabled:(BOOL)arg2;
- (void)setWindowButtonsEnabled:(BOOL)arg1;
- (BOOL)isUserInteractionEvent:(id)arg1;
@end

