//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPAppleScriptItem.h"

@interface SPAppleScriptTrack : SPAppleScriptItem
{
    shared_ptr_5269cdfc _trackInfo;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)dealloc;
- (id)cover;
- (id)spotifyURL;
- (id)popularity;
- (id)trackNumber;
- (id)playCount;
- (id)duration;
- (id)discNumber;
- (id)applescriptID;
- (id)title;
- (id)albumArtist;
- (id)album;
- (id)artist;
- (id)emptyStringOrStringFromString:(basic_string_a1f69cfb)arg1;
- (id)initWithTrackInfo:(shared_ptr_5269cdfc)arg1 parent:(id)arg2;

@end

