//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface SPAppleScriptItem : NSObject
{
    id parentItem;
    NSString *key;
}

- (void)dealloc;
- (id)objectSpecifier;
- (id)description;
- (id)title;
- (id)applescriptID;
- (id)initWithKey:(id)arg1 inParent:(id)arg2;

@end

