//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSInvocation;

@interface SPInvocationGrabber : NSObject
{
    id _object;
    NSInvocation *_invocation;
    int frameCount;
    char **frameStrings;
    BOOL backgroundAfterForward;
    BOOL onMainAfterForward;
    BOOL waitUntilDone;
}

@property BOOL waitUntilDone; // @synthesize waitUntilDone;
@property BOOL onMainAfterForward; // @synthesize onMainAfterForward;
@property BOOL backgroundAfterForward; // @synthesize backgroundAfterForward;
@property(retain, nonatomic) id object; // @synthesize object=_object;
@property(retain, nonatomic) NSInvocation *invocation; // @synthesize invocation=_invocation;
- (void)printBacktrace;
- (void)saveBacktrace;
- (void)invoke;
- (id)methodSignatureForSelector:(SEL)arg1;
- (void)forwardInvocation:(id)arg1;
- (void)runInBackground;
- (void)dealloc;
- (id)initWithObject:(id)arg1 stacktraceSaving:(BOOL)arg2;
- (id)initWithObject:(id)arg1;

@end

