//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface SPMediaKeyTap : NSObject
{
    struct OpaqueEventHandlerRef *_app_switching_ref;
    struct OpaqueEventHandlerRef *_app_terminating_ref;
    struct __CFMachPort *_eventPort;
    struct __CFRunLoopSource *_eventPortSource;
    struct __CFRunLoop *_tapThreadRL;
    BOOL _shouldInterceptMediaKeyEvents;
    id _delegate;
    NSMutableArray *_mediaKeyAppList;
}

+ (id)defaultMediaKeyUserBundleIdentifiers;
+ (BOOL)usesGlobalMediaKeyTap;
- (void)appTerminated:(struct ProcessSerialNumber)arg1;
- (void)appIsNowFrontmost:(struct ProcessSerialNumber)arg1;
- (void)mediaKeyAppListChanged;
- (void)eventTapThread;
- (void)handleAndReleaseMediaKeyEvent:(id)arg1;
- (void)setShouldInterceptMediaKeyEvents:(BOOL)arg1;
- (void)pauseTapOnTapThread:(BOOL)arg1;
- (BOOL)shouldInterceptMediaKeyEvents;
- (void)stopWatchingMediaKeys;
- (void)startWatchingMediaKeys;
- (void)stopWatchingAppSwitching;
- (void)startWatchingAppSwitching;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1;

@end

